# Site Info
title:              "Art by Lobo"
description:        "Here are my favorite drawings"

# Author Info
author_name:        Lobo

# Site Settings
baseurl:            "" # Base URL must end WITHOUT a slash, default: ""
permalink:          /:title # Post permalink
timezone:           America/New_York # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
language:           en-US
favicon:            /sitewideimg-red.png
logo:               /sitewideimg-red.png

# Pagination Settings
paginate_path: "/pg-:num/"
paginate: 5

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: elilobo
    
# Site Build
highlighter: rouge
markdown: kramdown
gems:
  - jekyll-sitemap
  - tzinfo
plugins:
  - jekyll-feed
  - jekyll-paginate

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:          "posts"
    values:
      layout:        "post"

